
<a href="https://numpy.org/"><img src="https://www.vectorlogo.zone/logos/numpy/numpy-ar21.svg" title="NumPy" alt="NumPy"></a>

# Introduction to NumPy

Some first NumPy steps

In [ ]:
import numpy as np

## Create a 1-D NumPy array

In [ ]:
# Create a NumPy array from a 'list' object
a = np.array([1, 2, 3])
a

array([1, 2, 3])

In [ ]:
# Create a NumPy array from a 'range' object
b = np.array(range(1, 4))
b

array([1, 2, 3])

In [ ]:
# Let's get some useful info
print(f"About array 'a' ({a}): type {type(a)}, shape ({a.shape})")
print(f"About array 'b' ({b}): type {type(b)}, shape ({b.shape})")

About array 'a' ([1 2 3]): type <class 'numpy.ndarray'>, shape ((3,))
About array 'b' ([1 2 3]): type <class 'numpy.ndarray'>, shape ((3,))


## NumPy array indexing

In [ ]:
# Modify an element
a[2] = 5
print(a)

[1 2 5]


## Create a 2-D NumPy array

In [ ]:
c = np.array(
    [[1,2,3],
     [3,4,5]]
)

print(c)
print(c.shape)

[[1 2 3]
 [3 4 5]]
(2, 3)


## Zeros

In [ ]:
zz = np.zeros((3,3), dtype=np.int)
zz

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

## Ones

In [ ]:
oo = np.ones((2,3), dtype=np.float)
oo

array([[1., 1., 1.],
       [1., 1., 1.]])

## Initialize a 2-D matrix

In [ ]:
matrix = np.full((3, 4), np.pi, dtype=np.float)
matrix

array([[3.14159265, 3.14159265, 3.14159265, 3.14159265],
       [3.14159265, 3.14159265, 3.14159265, 3.14159265],
       [3.14159265, 3.14159265, 3.14159265, 3.14159265]])

## Identity matrix

In [ ]:
identity = np.eye (6, dtype=np.int, k=-2)
identity


array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0],
       [0, 0, 0, 1, 0, 0]])

## Create a random number matrix

In [ ]:
r = np.random.random((5, 5))
r

array([[0.14612973, 0.02895515, 0.08550776, 0.35886233, 0.65336045],
       [0.93137211, 0.59677092, 0.89092499, 0.35697924, 0.46792325],
       [0.5385834 , 0.84019263, 0.83747245, 0.78850321, 0.3307995 ],
       [0.42830854, 0.25371214, 0.67476019, 0.13205145, 0.07161734],
       [0.72878516, 0.80597544, 0.85596548, 0.21116587, 0.71975558]])

## Managing rows and columns

In [ ]:
# New 2-D NumPy array
obj = np.array(
    [
     [1, 2, 3, 4],
     [5, 6, 7, 8],
     [9, 10, 11, 12]
     ]
)
obj

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
# Revert row order
obj[::-1]

array([[ 9, 10, 11, 12],
       [ 5,  6,  7,  8],
       [ 1,  2,  3,  4]])

## NumPy array boolean masking

In [ ]:
evens = (obj % 2 == 0)
evens

array([[False,  True, False,  True],
       [False,  True, False,  True],
       [False,  True, False,  True]])

In [ ]:
odds = (obj % 2 != 0)
odds

array([[ True, False,  True, False],
       [ True, False,  True, False],
       [ True, False,  True, False]])

## Matrix operations

In [ ]:
x = np.array([[1, 2], [3, 4]], dtype=np.int)
y = np.array([[5, 6], [7, 8]], dtype=np.int)
print(x)
print(y)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


In [ ]:
# Multiply element by element
np.multiply(x, y)

# This is equivalent
x * y

array([[ 5, 12],
       [21, 32]])

In [ ]:
# Transpose a matrix
x.T

array([[1, 3],
       [2, 4]])

In [ ]:
# Matrix multiplication
np.dot(x, y)

# This is equivalent
x @ y

array([[19, 22],
       [43, 50]])

## Reshape a matrix

In [ ]:
vector  = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])  
vector

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [ ]:
vector.reshape(2, 2, 3)

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [ ]:
# Can only specify one unknown dimension
vector.reshape(2, 2, -1)

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

## Create a 3-D NumPy array in a rapid way


In [ ]:
m = np.array([
              [[1,2,3],[1,2,3],[1,2,3]],
              [[1,2,3],[1,2,3],[1,2,3]],
              [[1,2,3],[1,2,3],[1,2,3]]
              ]
)
m

array([[[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]],

       [[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]],

       [[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]]])

In [ ]:
# Equilavent to the previous cell
mm = np.array([[[1, 2, 3]] * 3] * 3)
mm

array([[[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]],

       [[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]],

       [[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]]])